Quote from MMGL GitHub:
If you want to use your own data, you have to provide
- a csv.file which contains multi-modal features, and
- a multi-modal feature dict.

They also performed feature selection (ridge regression I think?) to reduce the number of features

Data Format:

In [1]:
import numpy as np
import pandas as pd

#explore_instance = np.load("/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/0/0.npy")
#print(explore_instance)

# demographic variables: age, sex, race, and smoking/non-smoking (n = 14)
demographics_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/Demographics.csv', index_col=0)
demographics_csv

,Female,Male,Asian,Black,Native American,Other,Pacific Islander,Unknown_race,White,SMOKER_N,SMOKER_Y,idx,split
current_age_yrs,,,,,,,,,,,,,
80.00,1,0,0,0,0,0,0,0,1,1,0,890,train
64.12,0,1,0,0,0,0,0,0,1,0,1,1879,train
93.42,0,1,0,0,0,0,0,0,1,0,1,1783,train
93.82,1,0,0,0,0,0,0,0,1,1,0,3896,test
71.78,1,0,0,0,0,0,0,0,1,1,0,1193,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71.04,0,1,0,0,0,1,0,0,0,1,0,3176,train
40.12,1,0,0,1,0,0,0,0,0,0,1,335,train
52.20,0,1,0,0,0,1,0,0,0,1,0,1000,val
59.40,0,1,0,0,0,0,0,0,1,1,0,860,train
81.29,1,0,0,0,0,0,0,0,1,1,0,897,test

In [2]:
# ICD codes relating to corresponding individuals over 12 months prior to CT scan (n = 284)
# frequency refers to the number of codes issued over the given time window
# presence refers to variables at time of CT scan ??
icd_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/ICD.csv', index_col=0)
icd_csv

,MATERNAL CAUSES OF PERINATAL MORBIDITY AND MORTALITY:frequency,OTHER CONDITIONS ORIGINATING IN THE PERINATAL PERIOD:frequency,COMPLICATIONS MAINLY RELATED TO PREGNANCY:frequency,COMPLICATIONS OCCURRING MAINLY IN THE COURSE OF LABOR AND DELIVERY:frequency,COMPLICATIONS OF THE PUERPERIUM:frequency,ECTOPIC AND MOLAR PREGNANCY:frequency,"NORMAL DELIVERY, AND OTHER INDICATIONS FOR CARE IN PREGNANCY, LABOR, AND DELIVERY:frequency",OTHER MATERNAL AND FETAL COMPLICATIONS:frequency,OTHER PREGNANCY WITH ABORTIVE OUTCOME:frequency,Anencephalus and similar anomalies:frequency,...,Symptoms involving digestive system:presence,Symptoms involving head and neck:presence,Symptoms involving nervous and musculoskeletal systems:presence,Symptoms involving respiratory system and other chest symptoms:presence,Symptoms involving skin and other integumentary tissue:presence,Symptoms involving urinary system:presence,SUPPLEMENTARY CLASSIFICATION OF EXTERNAL CAUSES OF INJURY AND POISONING:presence,SUPPLEMENTARY CLASSIFICATION OF FACTORS INFLUENCING HEALTH STATUS AND CONTACT WITH HEALTH SERVICES:presence,idx,split
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,84,test
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2248,test
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,2271,test
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1691,test
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3286,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1832,val
2488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,2487,val
2489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,1000,val
2490,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,2003,val
2491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,490,val

In [3]:
# inpatient variables (n = 1284)
inp_med_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/INP_MED.csv', index_col=0)
inp_med_csv

,"LAXATIVES, LOCAL/RECTAL:Binary",PLATELET AGGREGATION INHIBITORS:Binary,nan:Binary,"NOSE PREPARATIONS, VASOCONSTRICTORS(OTC):Binary","ANALGESIC/ANTIPYRETICS,NON-SALICYLATE:Binary",ANTIHYPERLIPIDEMIC - HMG COA REDUCTASE INHIBITORS:Binary,SELECTIVE SEROTONIN REUPTAKE INHIBITOR (SSRIS):Binary,"VASODILATORS,CORONARY:Binary",ANTIEMETIC/ANTIVERTIGO AGENTS:Binary,BETA-ADRENERGIC BLOCKING AGENTS:Binary,...,SELECTIVE SEROTONIN 5-HT2A INVERSE AGONISTS (SSIA):Frequeny,ANTINEOPLASTIC - HEDGEHOG PATHWAY INHIBITOR:Frequeny,ORGAN TRANSPLANTATION PRESERVATION SOLUTIONS:Frequeny,FEEDING DEVICES:Frequeny,"DRUGS TO TX GAUCHER DX-TYPE 1, SUBSTRATE REDUCING:Frequeny","TOPICAL PREPARATIONS,NON-MEDICINAL:Frequeny","ANTI-INFLAMMATORY, INTERLEUKIN-1 BETA BLOCKERS:Frequeny","ACNE AGENTS,SYSTEMIC:Frequeny",idx,split
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,84,test
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2248,test
2,0,0,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,2271,test
3,1,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1691,test
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3286,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1832,val
2488,1,0,0,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,2487,val
2489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1000,val
2490,1,0,0,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,2003,val
2491,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,490,val

In [4]:
# laboratory results variables (n = 46)
labs_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/LABS.csv', index_col=0)
labs_csv

,albumin:Binary,alk:Binary,ast:Binary,anion:Binary,bilirubin:Binary,bun:Binary,bun_cre:Binary,calcium:Binary,creatinine:Binary,d-dimer:Binary,...,hgb:Value,inr:Value,lactate:Value,platelet:Value,potassium:Value,ptt:Value,sodium:Value,wbc:Value,idx,split
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,1,1,1,1,1,1,0,0,1,0,...,0.0,0.0,0.0,116.0,0.0,0.0,0.0,0.3,84,test
1,1,1,1,1,1,1,0,0,1,0,...,0.0,0.0,0.0,655.0,0.0,0.0,0.0,13.8,2248,test
2,1,1,1,1,1,1,0,0,1,0,...,0.0,1.3,0.0,356.0,0.0,15.9,0.0,6.8,2271,test
3,1,1,1,1,1,1,0,0,1,0,...,0.0,0.0,1.8,426.0,0.0,0.0,0.0,10.0,1691,test
4,1,1,1,1,1,1,0,0,1,0,...,0.0,2.0,0.0,131.0,0.0,21.7,0.0,4.0,3286,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487,1,1,1,1,1,1,0,0,1,0,...,0.0,1.2,0.0,193.0,0.0,13.8,0.0,5.8,1832,val
2488,1,1,1,1,1,1,0,0,1,0,...,0.0,3.3,0.0,172.0,0.0,33.3,0.0,6.4,2487,val
2489,1,1,1,1,1,1,0,0,1,0,...,0.0,1.1,1.9,256.0,0.0,14.5,0.0,15.0,1000,val
2490,1,1,1,1,1,1,0,0,1,0,...,0.0,2.3,0.0,248.0,0.0,24.5,0.0,5.6,2003,val
2491,1,1,1,1,1,1,0,0,1,0,...,0.0,0.0,0.0,238.0,0.0,0.0,0.0,4.2,490,val

In [5]:
# Patient index, reponse, PE type 
labels_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/Labels.csv', index_col=0)
labels_csv

       idx  label    pe_type  split
0     1436      0        NaN  train
1     1880      1  segmental  train
2     2738      0        NaN    val
3     2883      0        NaN  train
4     2302      1  segmental  train
...    ...    ...        ...    ...
1832  1516      0        NaN  train
1833   127      0        NaN    val
1834  2876      1    central   test
1835  1875      0        NaN  train
1836   610      0        NaN  train

[1837 rows x 4 columns]

In [6]:
# Outpatient variables (n = 1284)
# Each outpatient variable corresponds to an inpatient variable (in the same column position?)
out_med_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/OUT_MED.csv', index_col=0)
out_med_csv_max_values = out_med_csv.max()
out_med_csv_max_values

Outpatient_LAXATIVES, LOCAL/RECTAL:Binary                                1
Outpatient_PLATELET AGGREGATION INHIBITORS:Binary                        1
Outpatient_nan:Binary                                                    0
Outpatient_NOSE PREPARATIONS, VASOCONSTRICTORS(OTC):Binary               1
Outpatient_ANALGESIC/ANTIPYRETICS,NON-SALICYLATE:Binary                  1
                                                                      ...
Outpatient_TOPICAL PREPARATIONS,NON-MEDICINAL:Frequeny                   0
Outpatient_ANTI-INFLAMMATORY, INTERLEUKIN-1 BETA BLOCKERS:Frequeny       0
Outpatient_ACNE AGENTS,SYSTEMIC:Frequeny                                 0
idx                                                                   3957
split                                                                  val
Length: 1284, dtype: object

In [7]:
explore_instance = np.load("/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/images/0.npy")
n_slices = 180
#list(range(explore_instance.shape[0]))
slices_to_take = np.unique([i * n_slices // explore_instance.shape[0] for i in list(range(explore_instance.shape[0]))], return_index=True)[1]
explore_instance = explore_instance[slices_to_take, ::2, ::2]

In [8]:
# vitals variables (n = 11)
vitals_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/Vitals.csv', index_col=0)
vitals_csv = vitals_csv[(vitals_csv != -10000).all(axis=1) & (vitals_csv != 0).all(axis=1)].drop_duplicates("idx")
# vitals_csv = vitals_csv.isin(labels_csv.idx)
#full_vitals_idx = vitals_csv.idx

In [ ]:
# vitals variables (n = 11)
vitals_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/Vitals.csv', index_col=0)
vitals_csv = vitals_csv[(vitals_csv != -10000).all(axis=1) & (vitals_csv != 0).all(axis=1)]
vitals_csv = vitals_csv.drop_duplicates("idx")
#vitals_csv.hist()
full_vitals_idx = vitals_csv.idx

#images

Fetching Image Data For: 3147
0.09437184
Fetching Image Data For: 2832
0.18874368
Fetching Image Data For: 15
0.28311552
Fetching Image Data For: 3505
0.37748736
Fetching Image Data For: 227
0.4718592
Fetching Image Data For: 2467
0.56623104
Fetching Image Data For: 2440
0.66060288
Fetching Image Data For: 3568
0.75497472
Fetching Image Data For: 2861
0.84934656
Fetching Image Data For: 3185
0.9437184
Fetching Image Data For: 614
1.03809024
Fetching Image Data For: 306
1.13246208
Fetching Image Data For: 724
1.22683392
Fetching Image Data For: 3854
1.32120576
Fetching Image Data For: 2281
1.4155776
Fetching Image Data For: 305
1.50994944
Fetching Image Data For: 1745
1.60432128
Fetching Image Data For: 3741
1.69869312
Fetching Image Data For: 792
1.79306496
Fetching Image Data For: 1220
1.8874368
Fetching Image Data For: 242
1.98180864
Fetching Image Data For: 3619
2.07618048
Fetching Image Data For: 2695
2.17055232
Fetching Image Data For: 226
2.26492416
Fetching Image Data For: 2787
2.359296
Fetching Image Data For: 2824
2.45366784
Fetching Image Data For: 1719
2.54803968
Fetching Image Data For: 1922
2.64241152
Fetching Image Data For: 397
2.73678336
Fetching Image Data For: 2163
2.8311552
Fetching Image Data For: 1351
2.92552704
Fetching Image Data For: 2710
3.01989888
Fetching Image Data For: 1671
3.11427072
Fetching Image Data For: 1166
3.20864256
Fetching Image Data For: 557
3.3030144
Fetching Image Data For: 296
3.39738624
Fetching Image Data For: 1386
3.49175808
Fetching Image Data For: 1904
3.58612992
Fetching Image Data For: 833
3.68050176
Fetching Image Data For: 992
3.7748736
Fetching Image Data For: 3602
3.86924544
Fetching Image Data For: 2629
3.96361728
Fetching Image Data For: 3812
4.05798912
Fetching Image Data For: 935
4.15236096
Fetching Image Data For: 1750
4.2467328
Fetching Image Data For: 3633
4.34110464
Fetching Image Data For: 2488
4.43547648
Fetching Image Data For: 112
4.52984832
Fetching Image Data For: 2403
4.62422016
Fetching Image Data For: 1575
4.718592
Fetching Image Data For: 612
4.81296384
Fetching Image Data For: 2694
4.90733568
Fetching Image Data For: 3869
5.00170752
Fetching Image Data For: 2539
5.09607936
Fetching Image Data For: 1612
5.1904512
Fetching Image Data For: 1593
5.28482304
Fetching Image Data For: 1595
5.37919488
Fetching Image Data For: 706
5.47356672
Fetching Image Data For: 1932
5.56793856
Fetching Image Data For: 2875
5.6623104
Fetching Image Data For: 825
5.75668224
Fetching Image Data For: 1441
5.85105408
Fetching Image Data For: 561
5.94542592
Fetching Image Data For: 3327
6.03979776
Fetching Image Data For: 1752
6.1341696
Fetching Image Data For: 482
6.22854144
Fetching Image Data For: 779
6.32291328
Fetching Image Data For: 662
6.41728512
Fetching Image Data For: 3121
6.51165696
Fetching Image Data For: 3517
6.6060288
Fetching Image Data For: 2732
6.70040064
Fetching Image Data For: 3930
6.79477248
Fetching Image Data For: 2755
6.88914432
Fetching Image Data For: 2680
6.98351616
Fetching Image Data For: 2973
7.077888
Fetching Image Data For: 2410
7.17225984
Fetching Image Data For: 886
7.26663168
Fetching Image Data For: 1303
7.36100352
Fetching Image Data For: 2378
7.45537536
Fetching Image Data For: 3115
7.5497472
Fetching Image Data For: 1066
7.64411904
Fetching Image Data For: 1684
7.73849088
Fetching Image Data For: 3036
7.83286272
Fetching Image Data For: 985
7.92723456
Fetching Image Data For: 2361
8.0216064
Fetching Image Data For: 2449
8.11597824
Fetching Image Data For: 2691
8.21035008
Fetching Image Data For: 2272
8.30472192
Fetching Image Data For: 177
8.39909376
Fetching Image Data For: 3047
8.4934656
Fetching Image Data For: 2942
8.58783744
Fetching Image Data For: 1422
8.68220928
Fetching Image Data For: 1305
8.77658112
Fetching Image Data For: 3402
8.87095296
Fetching Image Data For: 19
8.9653248
Fetching Image Data For: 3768
9.05969664
Fetching Image Data For: 284
9.15406848
Fetching Image Data For: 3951
9.24844032
Fetching Image Data For: 1927
9.34281216
Fetching Image Data For: 1806
9.437184
Fetching Image Data For: 530
9.53155584
Fetching Image Data For: 1794
9.62592768
Fetching Image Data For: 2807
9.72029952
Fetching Image Data For: 2062
9.81467136
Fetching Image Data For: 523
9.9090432
Fetching Image Data For: 2647
10.00341504
Fetching Image Data For: 3760
10.09778688
Fetching Image Data For: 2393
10.19215872
Fetching Image Data For: 2487
10.28653056

In [ ]:
import os

# Patient index, reponse, PE type 
labels_csv = pd.read_csv('/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/Labels.csv', index_col=0)
labels_csv

image_paths = pd.DataFrame({"idx": [], "path": []})
for i in labels_csv.idx:
    image_path = os.path.join("/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/images/" + str(i) + ".npy")
    image_paths.loc[len(image_paths)] = [i, image_path]

min_slices = 210
# for i in full_vitals_idx:
#     image_path = image_paths[image_paths.idx == i]
#     image = np.load(image_path.iat[0, 1])
#     print("shape of " + str(i) + ": " + str(image.shape))
#     min_z = min(min_z, image.shape[0])
#     print(min_z)

n_slices = 180
images = np.ndarray(shape=(0, n_slices * 256 * 256))
for i in full_vitals_idx:
    print("Fetching Image Data For: " + str(i))
    image_path = image_paths[image_paths.idx == i]
    image = np.load(image_path.iat[0, 1])
    # variably reduce the number of slices (given n_slices <= min_slices)
    slices_to_take = np.unique([i * n_slices // image.shape[0] for i in list(range(image.shape[0]))], return_index=True)[1]
    image = image[slices_to_take, ::2, ::2]
    images = np.vstack((images, np.ravel(image)))
    print(images.nbytes / 1000000000)

In [ ]:
np.save("images_with_full_vitals.npy", images)

5e-324

In [ ]:
images = np.load("images_with_full_vitals.npy")

In [ ]:
from sklearn.decomposition import IncrementalPCA
# # Dealing with images

# # convert to connectivity graph -> clustering
# explore_instance = np.load("/home/mrdon/radfusion/multimodalpulmonaryembolismdataset/0/0.npy")
# ei_shape = explore_instance.shape
# #vectorized_ei = np.reshape(explore_instance, ei_shape[0] * ei_shape[1] * ei_shape[2])
# vector_ei = np.ravel(explore_instance)



full_vitals_labels_idx = labels_csv.idx.isin(full_vitals_idx)
target_response = labels_csv[full_vitals_labels_idx].label
target_response
n_features = len(target_response)
n_features
# ipca = IncrementalPCA(n_components=109, batch_size=100*n_features)
# dim_reduced_images = lda.fit_transform(X=images, y=target_response)


# # compress the image here before calculating connivity graph

# # edge weights are based on the gradient between nodes (?)
# connectivity = fe.img_to_graph(explore_instance)

:

In [ ]:


# import sys
# print(connectivity.shape)
# data_size = connectivity.data.nbytes
# row_size = connectivity.row.nbytes
# col_size = connectivity.col.nbytes

# mem_size = data_size + row_size + col_size
# (mem_size) / 1000000

# slc_200 = explore_instance[400, 0:512, 0:512]



# connectivity_array = connectivity.toarray()
# ut_idx = np.triu_indices_from(connectivity_array, k=1)
# stacked_graph = np.vstack(connectivity_array[ut_idx])


# get UT indices, send to 1D array, concat together to get num_patients x nrow_connectivity
# it seems a bit early for ridge regression (on one hundred million parameters!)
# so some sort of clustering beforehand for dimensionality reduction? (PCA)

1